import { Component } from '@angular/core';
import { AngularMaterialModule } from '../../../assets/angular-material/angular-material.module';
import { CommonModule } from '@angular/common';
import { ParkingSpaceCardComponent } from './components/parking-space-card/parking-space-card.component';
import { ParkingCard } from './parkingCard';



@Component({
  selector: 'app-parking',
  standalone: true,
  imports: [AngularMaterialModule, ParkingSpaceCardComponent, CommonModule],
  templateUrl: './parking.component.html',
  styleUrl: './parking.component.scss'
})
export class ParkingComponent {

  parkingSpaces: ParkingCard[] = [
    { id: 1, name: 'A1', status: 'Occupied', vehiclePlate: 'KRA 1A234' },
    { id: 2, name: 'A2', status: 'Occupied', vehiclePlate: 'WWA 5B567' },
    { id: 3, name: 'A3', status: 'Available', vehiclePlate: '' },
    { id: 4, name: 'A4', status: 'Reserved', vehiclePlate: '' },
    { id: 5, name: 'A5', status: 'Occupied', vehiclePlate: 'GDA 8C890' },
    { id: 6, name: 'A6', status: 'Available', vehiclePlate: '' },
    { id: 7, name: 'A7', status: 'Available', vehiclePlate: '' },
    { id: 8, name: 'A8', status: 'Maintenance', vehiclePlate: '' },
    { id: 9, name: 'A9', status: 'Occupied', vehiclePlate: 'POZ 1D123' },
    { id: 10, name: 'A10', status: 'Occupied', vehiclePlate: 'WRO 4E456' },
    { id: 11, name: 'A11', status: 'Available', vehiclePlate: '' },
    { id: 12, name: 'A12', status: 'Occupied', vehiclePlate: 'LC 7F789' },
    { id: 13, name: 'A13', status: 'Available', vehiclePlate: '' },
    { id: 14, name: 'A14', status: 'Occupied', vehiclePlate: 'SJZ 0G012' },
    { id: 15, name: 'A15', status: 'Available', vehiclePlate: '' },
    { id: 16, name: 'A16', status: 'Occupied', vehiclePlate: 'BIA 3H345' },
    { id: 17, name: 'A17', status: 'Available', vehiclePlate: '' },
    { id: 18, name: 'A18', status: 'Occupied', vehiclePlate: 'RZE 6J678' },
    { id: 19, name: 'A19', status: 'Reserved', vehiclePlate: '' },
    { id: 20, name: 'A20', status: 'Available', vehiclePlate: '' },
    { id: 21, name: 'A21', status: 'Occupied', vehiclePlate: 'KRA 9K901' },
    { id: 22, name: 'A22', status: 'Occupied', vehiclePlate: 'EL 2L234' },
    { id: 23, name: 'A23', status: 'Available', vehiclePlate: '' },
    { id: 24, name: 'A24', status: 'Occupied', vehiclePlate: 'GD 5M567' },
    { id: 25, name: 'A25', status: 'Available', vehiclePlate: '' },
    { id: 26, name: 'B1', status: 'Occupied', vehiclePlate: 'ZST 8N890' },
    { id: 27, name: 'B2', status: 'Available', vehiclePlate: '' },
    { id: 28, name: 'B3', status: 'Available', vehiclePlate: '' },
    { id: 29, name: 'B4', status: 'Occupied', vehiclePlate: 'KTA 1P123' },
    { id: 30, name: 'B5', status: 'Occupied', vehiclePlate: 'KR 4R456' },
    { id: 31, name: 'B6', status: 'Available', vehiclePlate: '' },
    { id: 32, name: 'B7', status: 'Occupied', vehiclePlate: 'SC 7S789' },
    { id: 33, name: 'B8', status: 'Available', vehiclePlate: '' },
    { id: 34, name: 'B9', status: 'Occupied', vehiclePlate: 'LUB 0T012' },
    { id: 35, name: 'B10', status: 'Available', vehiclePlate: '' },
    { id: 36, name: 'B11', status: 'Occupied', vehiclePlate: 'PO 3U345' },
    { id: 37, name: 'B12', status: 'Available', vehiclePlate: '' },
    { id: 38, name: 'B13', status: 'Occupied', vehiclePlate: 'ERA 6V678' },
    { id: 39, name: 'B14', status: 'Reserved', vehiclePlate: '' },
    { id: 40, name: 'B15', status: 'Available', vehiclePlate: '' },
    { id: 41, name: 'B16', status: 'Occupied', vehiclePlate: 'DW 9W901' },
    { id: 42, name: 'B17', status: 'Maintenance', vehiclePlate: '' },
    { id: 43, name: 'B18', status: 'Available', vehiclePlate: '' },
    { id: 44, name: 'B19', status: 'Occupied', vehiclePlate: 'FG 5Y567' },
    { id: 45, name: 'B20', status: 'Available', vehiclePlate: '' },
    { id: 46, name: 'B21', status: 'Occupied', vehiclePlate: 'TK 8Z890' },
    { id: 47, name: 'B22', status: 'Available', vehiclePlate: '' },
    { id: 48, name: 'B23', status: 'Available', vehiclePlate: '' },
    { id: 49, name: 'B24', status: 'Occupied', vehiclePlate: 'WW 1A123' },
    { id: 50, name: 'B25', status: 'Occupied', vehiclePlate: 'NE 4B456' },
    { id: 51, name: 'C1', status: 'Available', vehiclePlate: '' },
    { id: 52, name: 'C2', status: 'Occupied', vehiclePlate: 'BI 7C789' },
    { id: 53, name: 'C3', status: 'Available', vehiclePlate: '' },
    { id: 54, name: 'C4', status: 'Occupied', vehiclePlate: 'KBC 0D012' },
    { id: 55, name: 'C5', status: 'Available', vehiclePlate: '' },
    { id: 56, name: 'C6', status: 'Occupied', vehiclePlate: 'GKS 3E345' },
    { id: 57, name: 'C7', status: 'Available', vehiclePlate: '' },
    { id: 58, name: 'C8', status: 'Occupied', vehiclePlate: 'PKN 6F678' },
    { id: 59, name: 'C9', status: 'Reserved', vehiclePlate: '' },
    { id: 60, name: 'C10', status: 'Available', vehiclePlate: '' },
    { id: 61, name: 'C11', status: 'Occupied', vehiclePlate: 'SBL 9G901' },
    { id: 62, name: 'C12', status: 'Occupied', vehiclePlate: 'TKA 2H234' },
    { id: 63, name: 'C13', status: 'Available', vehiclePlate: '' },
    { id: 64, name: 'C14', status: 'Occupied', vehiclePlate: 'CNA 5J567' },
    { id: 65, name: 'C15', status: 'Available', vehiclePlate: '' },
    { id: 66, name: 'C16', status: 'Occupied', vehiclePlate: 'DWR 8K890' },
    { id: 67, name: 'C17', status: 'Available', vehiclePlate: '' },
    { id: 68, name: 'C18', status: 'Available', vehiclePlate: '' },
    { id: 69, name: 'C19', status: 'Occupied', vehiclePlate: 'EOP 1L123' },
    { id: 70, name: 'C20', status: 'Occupied', vehiclePlate: 'FMI 4M456' },
    { id: 71, name: 'C21', status: 'Available', vehiclePlate: '' },
    { id: 72, name: 'C22', status: 'Occupied', vehiclePlate: 'GKW 7N789' },
    { id: 73, name: 'C23', status: 'Available', vehiclePlate: '' },
    { id: 74, name: 'C24', status: 'Occupied', vehiclePlate: 'HGR 0P012' },
    { id: 75, name: 'C25', status: 'Available', vehiclePlate: '' },
    { id: 76, name: 'D1', status: 'Occupied', vehiclePlate: 'IRT 3R345' },
    { id: 77, name: 'D2', status: 'Available', vehiclePlate: '' },
    { id: 78, name: 'D3', status: 'Occupied', vehiclePlate: 'JGI 6S678' },
    { id: 79, name: 'D4', status: 'Reserved', vehiclePlate: '' },
    { id: 80, name: 'D5', status: 'Available', vehiclePlate: '' },
    { id: 81, name: 'D6', status: 'Occupied', vehiclePlate: 'KLI 9T901' },
    { id: 82, name: 'D7', status: 'Maintenance', vehiclePlate: '' },
    { id: 83, name: 'D8', status: 'Available', vehiclePlate: '' },
    { id: 84, name: 'D9', status: 'Occupied', vehiclePlate: 'LOD 5V567' },
    { id: 85, name: 'D10', status: 'Available', vehiclePlate: '' },
    { id: 86, name: 'D11', status: 'Occupied', vehiclePlate: 'MLE 8W890' },
    { id: 87, name: 'D12', status: 'Available', vehiclePlate: '' },
    { id: 88, name: 'D13', status: 'Available', vehiclePlate: '' },
    { id: 89, name: 'D14', status: 'Occupied', vehiclePlate: 'NKE 1X123' },
    { id: 90, name: 'D15', status: 'Occupied', vehiclePlate: 'OPO 4Y456' },
    { id: 91, name: 'D16', status: 'Available', vehiclePlate: '' },
    { id: 92, name: 'D17', status: 'Occupied', vehiclePlate: 'PGE 7Z789' },
    { id: 93, name: 'D18', status: 'Available', vehiclePlate: '' },
    { id: 94, name: 'D19', status: 'Occupied', vehiclePlate: 'RLE 0A012' },
    { id: 95, name: 'D20', status: 'Available', vehiclePlate: '' },
    { id: 96, name: 'D21', status: 'Occupied', vehiclePlate: 'SBE 3B345' },
    { id: 97, name: 'D22', status: 'Available', vehiclePlate: '' },
    { id: 98, name: 'D23', status: 'Occupied', vehiclePlate: 'TBU 6C678' },
    { id: 99, name: 'D24', status: 'Reserved', vehiclePlate: '' },
    { id: 100, name: 'D25', status: 'Available', vehiclePlate: '' }
  ]
}
